// webpack-react/button-example.jsx
import * as React from "react";
import { Button } from "devextreme-react/button";
import { alert } from "devextreme/ui/dialog";

export default class extends React.Component {
    handleClick = () => {
        alert("Hello world!", "", false);
    }

    render() {
        return (
            <Button 
                text="Say 'Hello world'" 
                onClick={this.handleClick}
            />
        );
    }
}

// webpack-vue/components/button-example.vue
<template>
    <dx-button
    text="Say 'Hello world'"
    @click="showAlert" />
</template>

<script>
import { DxButton } from "devextreme-vue/button";
import { alert } from "devextreme/ui/dialog";

export default {
  components: {
    DxButton
  },
  methods: {
    showAlert() {
      alert("Hello world!", "", false);
    }
  }
};
</script>
